# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='priority',
            field=models.IntegerField(default=-2),
        ),
    ]
