# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_talk_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
